name: CI

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Create .env
                run: |
                    {
                        echo VUE_APP_SERVER_HOST=${{ secrets.SERVER_HOST }}
                        echo VUE_APP_SERVER_PORT=${{ secrets.SERVER_PORT }}
                        echo VUE_APP_TOKEN=${{ secrets.TOKEN }}
                    } > .env

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: '14.16.1'
            - run: npm ci
            - run: npm run build

            - name: Cleanup remote
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: rm -rf ${{ secrets.REMOTE_TARGET }}

            - name: Copy files
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: "-rltgoDzvO --delete"
                  SOURCE: "dist/"
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
                  EXCLUDE: ""

            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      source ~/.bashrc
                      pm2 restart tg-bot >/dev/null 2>&1
